routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'UsersController@listAllUsersAction')->name('all-users');

Route::prefix('{user_id}')->group(function () {
    Route::get('/create_new_job', 'JobsController@displayNewJobFormAction')->name('create-new-job-get');
    Route::post('/create_new_job', 'JobsController@createNewJobAction')->name('create-new-job-post');
});

Route::get('/verify_new_job/{job_id}/{token}', 'JobsController@displayPendingJobAction')->name('verify-new-job-get');
Route::post('/approve_job/{job_id}/{token}', 'JobsController@approveJobAction')->name('job-approve');
Route::post('/mark_as_spam/{job_id}/{token}', 'JobsController@markAsSpamAction')->name('job-mark-as-spam');

Route::get('all_jobs', 'JobsController@listAllJobsAction')->name('all-jobs');
Route::get('all_users', 'UsersController@listAllUsersAction')->name('all-users');

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use App\Jobs;
use App\Users;
use App\Http\Controllers\Controller;

class UsersController extends Controller
{

     public function listAllUsersAction () {

         $user_list = Users::withCount('jobs')->paginate(10);
         return view('pages.user_list')->with(['user_list' => $user_list]);
     }
}

resources/views/container/job_list_container.blade.php
<div class='container'>
    <table>
        <tr>
            <th>job id</th>
            <th>title</th>
            <th>job_status</th>
        </tr>

        @foreach ($job_list as $job)
            <tr>
                <td>{{ $job->job_id }}</td>
                <td>{{ $job->title }}</td>
                <td>{{ $job->job_status }}</td>
            </tr>
        @endforeach

    </table>

    {{ $job_list->links() }}
</div>

resources/views/container/job_posting_cointainer.blade.php
<div class='container'>
    <div class='row justify-content-center'>
        <div class='col-md-8'>
            Job title: {{$job_data->title}}
        </div>
    </div>
    <br><br><br>
    <div class='row justify-content-center'>
        <div class='col-md-8'>
            Job description: {{$job_data->description}}
        </div>
    </div>

    <div class='row justify-content-center'>
        <div class='col-md-8'>
            <form method='POST' action="{{route('job-approve', ['token'=> $job_data->token, 'job_id'=> $job_data->job_id] ) }}">
                @csrf
                <div class='form-group row mb-0'>
                    <div class='col-md-6 offset-md-4'>
                        <button type='submit' class='btn btn-primary'>Approve</button>
                    </div>
                </div>
            </form>
            <br><br><br>
            <form method='POST' action="{{route('job-mark-as-spam', ['token'=> $job_data->token, 'job_id'=> $job_data->job_id] ) }}">
                @csrf
                <div class='form-group row mb-0'>
                    <div class='col-md-6 offset-md-4'>
                        <button type='submit' class='btn btn-danger'>Mark as spam</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/container/user_list_container.blade.php
<div class='container'>
    <table class="table">
        <thead>
        <tr>
            <th>user id</th>
            <th>name</th>
            <th>email</th>
            <th>level</th>
            <th>Jobs Count</th>
            <th>created_at</th>
            <th>updated_at</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($user_list as $user)
            <tr>
                <td>{{ $user->user_id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->user_level }}</td>
                <td>{{ $user->jobs_count }}</td>
                <td>{{ $user->created_at }}</td>
                <td>{{ $user->updaterd_at }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{ $user_list->links() }}
</div>